// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhbYWIO96vqbNOfDd4QipmYlloaik-cuI',
    appId: '1:43346840164:web:503f0ccb0279a0c6c66d71',
    messagingSenderId: '43346840164',
    projectId: 'flutterapp-19c17',
    authDomain: 'flutterapp-19c17.firebaseapp.com',
    storageBucket: 'flutterapp-19c17.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhbYWIO96vqbNOfDd4QipmYlloaik-cuI',
    appId: '1:43346840164:web:503f0ccb0279a0c6c66d71',
    messagingSenderId: '43346840164',
    projectId: 'flutterapp-19c17',
    authDomain: 'flutterapp-19c17.firebaseapp.com',
    storageBucket: 'flutterapp-19c17.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF0em4AcWZQSUzApDRALh1pzPtPCHicLg',
    appId: '1:43346840164:ios:b772d7e4976d3b6ac66d71',
    messagingSenderId: '43346840164',
    projectId: 'flutterapp-19c17',
    storageBucket: 'flutterapp-19c17.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF0em4AcWZQSUzApDRALh1pzPtPCHicLg',
    appId: '1:43346840164:ios:b772d7e4976d3b6ac66d71',
    messagingSenderId: '43346840164',
    projectId: 'flutterapp-19c17',
    storageBucket: 'flutterapp-19c17.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDpZwaYlluRSWejgPo0Y4TZUTlcnfTLTQ',
    appId: '1:43346840164:android:71b8ce5258be7327c66d71',
    messagingSenderId: '43346840164',
    projectId: 'flutterapp-19c17',
    storageBucket: 'flutterapp-19c17.firebasestorage.app',
  );

}